# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 917936e9755f644cf4f17ec53dca8aeb15f15fa7e4ab9d3f196d07253a90024cf93a61b9e3c76e5714545655673f5d57ccb0ac05914569000b2b3deed9979abe

test:
  secret_key_base: 0aa7c6395d452178ca449ea44a81709c072ed92f15d82ab32bb40bcd7e32bc43dc2b6c0d2c4f463e5360783050e1a5d545a3b962c9267300614c1ed5688e14bd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
